### ISSUE TITLE
Emscripten port

### ISSUE THREAD

**Issue by midzer** [freegish/freegish#23]
Hi,

I am working on a port of freegish for the web. Using Emscripten, I came pretty far, but there are graphical issues/flickering:

https://freegish.netlify.app/

I dont know exactly what is causing this, but probably some custom timing function in freegish code. Any1 have an idea where  to look?

edit: I've found the culprit: https://github.com/midzer/freegish/blob/a6e29b57dcedda60e2fccf3ddad38365f22ab731/src/sdl/event.c#L39

**Comment by harshavardhan-b20** [comment]
Hello,

I'm excited about contributing to this issue and believe it aligns well with my skills and interests. Could you please assign me to work on this? I'm ready to dive in, discuss the details, and start contributing.

Thank you!
Harshavardhan Bellamkonda

**Comment by midzer** [comment]
Emscripten port is working now. Closing for good.
